apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
resources:
  - namespace.yaml
  - HelmRelease-grafana.yaml
  - HelmRelease-loki.yaml
  - HelmRelease-prometheus.yaml
  - HelmRelease-promtail.yaml

