apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: monitoring
resources:
  - namespace.yaml
  - helmrepo.yaml
  - prometheus-helmrelease.yaml
  - loki-helmrelease.yaml
  - grafana-helmrelease.yaml
  - promtail-helmrelease.yaml
