---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loggers-controllers
  namespace: flux-system
spec:
  interval: 1h
  retryInterval: 2m
  timeout: 10m
  path: ./workloads/monitoring/controllers
  prune: true
  wait: true
  sourceRef:
    kind: GitRepository
    name: flux-system

---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: loggers-configs
  namespace: flux-system
spec:
  dependsOn:
    - name: loggers-controllers
  interval: 1h
  retryInterval: 2m
  timeout: 5m
  prune: true
  wait: true
  path: ./workloads/monitoring/configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  
