apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wordpress-stack
  namespace: flux-system
spec:
  interval: 1m
  path: ./workloads/wordpress  
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
