# flux-system/wordpress-kustomization.yaml
apiVersion: kustomize.toolkit.fluxcd.io/v1beta2
kind: Kustomization
metadata:
  name: wordpress-stack
  namespace: flux-system
spec:
  interval: 5m
  path: ./wordpress    # path in your Git repository where manifests live
  prune: true
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system
  validation: client
